---
title: "01_load"
format:
  html:
    embed-resources: true
editor: visual
---

# 01_Load

## Libraries

```{r 01_libary, message=FALSE, running=FALSE}
library(tidyverse)
library(here)
```

# Loading Data

Downloading data from dropbox containing the proteomics dataset.

```{r 01_download}
#defining path to store data in the folder data_raw
raw_dir <- here("data/_raw")
data_file <- "mouse_cell_stages.zip"
data_location <- "https://www.dropbox.com/scl/fi/d63o8sgp03fyu2s6tsqau/group_6_data.zip?rlkey=50z2rrfaowoizqivttdmyym2i&st=kngr6y9j&dl=1"


# Dropbox url
url <- "https://www.dropbox.com/scl/fi/xo2tgbhknzelxazhu6qcg/group_6_data_2.zip?rlkey=q0awssn7v4vgi4xfpk2pgl142&st=blph5keq&dl=1"


if( !dir.exists(raw_dir) ){ # Check if the path already exists and creates it if it doesn't  exist
  dir.create(path = raw_dir)
} 
if( !file.exists(str_c(raw_dir, data_file, sep = "/")) ){ # Downloads the data unless it is not already downloaded
  download.file(
    url = data_location,
    destfile = str_c(raw_dir, data_file, sep = "/"))
}

# Unzip the proteomics data
unzip(str_c(raw_dir, data_file, sep = "/"), exdir = raw_dir)
```

```{r 01_read_csv, message=FALSE, running=FALSE}

# read in csv files for all cell populations

df_hsc <- read_csv2(file = here("data/_raw/group6_data_HSC_Report.csv"), na="NaN")
df_mep <- read_csv2(file = here("data/_raw/group6_data_MEP_Report.csv"), na="NaN")
df_gmp <- read_csv2(file = here("data/_raw/group6_data_GMP_Report.csv"), na="NaN")
df_clp <- read_csv2(file = here("data/_raw/group6_data_CLP_Report.csv"), na="NaN")
df_cmp <- read_csv2(file = here("data/_raw/group6_data_CMP_Report.csv"), na="NaN")


# read in tsv file for mus musculus uniprot file

.df_uniprot_mouse <- read_csv2(file = here("raw_data/uniprotkb_mus_musculus.tsv"), na= "NaN")


#| echo: false
#| eval: false

```


### Save the data-file for 02_clean.qmd

```{r 01_write_csv}
project_path = here()
setwd(project_path)

write_tsv(df_hsc, file = here("data/01_hsc.tsv.gz"))
write_tsv(df_mep, file = here("data/01_mep.tsv.gz"))
write_tsv(df_gmp, file = here("data/01_gmp.tsv.gz"))
write_tsv(df_clp, file = here("data/01_clp.tsv.gz"))
write_tsv(df_cmp, file = here("data/01_cmp.tsv.gz"))

write_tsv(.df_uniprot_mouse, "data/01_dat_load_uniprot_mouse.tsv")

```
