---
title: "01_load"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
```

# Loading Data

##### Before sharepoint API issue is resolved, load data directly from local machine

```{r}

# read in csv files for all cell populations
#loading data
#setwd(getwd())
#setwd("/home/people/s194428/projects/project_group6")
#setwd("/home/people/s215025/Projects/group_6_project")
#setwd("/Users/cxm393/Code/R/R for Bioscience/group_6_project")


df_hsc <- read_csv2(file = "local_data/group6_data_HSC_Report.csv", na= "NaN")
df_mep <- read_csv2(file = "local_data/group6_data_MEP_Report.csv", na= "NaN")
df_gmp <- read_csv2(file = "local_data/group6_data_GMP_Report.csv", na= "NaN")
df_clp <- read_csv2(file = "local_data/group6_data_CLP_Report.csv", na= "NaN")
df_cmp <- read_csv2(file = "local_data/group6_data_CMP_Report.csv", na= "NaN")

#| echo: false
#| eval: false

```

```{r}
# write tsv files
project_path = here()
setwd(project_path)
dir.create("data")
write_tsv(df_hsc, "data/01_dat_load_hsc.tsv")
write_tsv(df_mep, "data/01_dat_load_mep.tsv")
write_tsv(df_gmp, "data/01_dat_load_gmp.tsv")
write_tsv(df_clp, "data/01_dat_load_clp.tsv")
write_tsv(df_cmp, "data/01_dat_load_cmp.tsv")
```
