---
title: "04_describe"
format: html
editor: visual
---

## Library

```{r}
library("tidyverse")
```

## Load Data

```{r}
df_long <- read_tsv(file = here("data/02_dat_clean.tsv"))
```

### 1. Raw Data

|                     | hsc  | cmp  | gmp  | clp  | mep  |
|---------------------|------|------|------|------|------|
| No. of observations | 2196 | 1986 | 2291 | 2382 | 2691 |
| No. of variables    | 6    | 6    | 6    | 7    | 6    |
| No. of replicates   | 4    | 4    | 4    | 5    | 4    |

-   CV's

-   

## Normalization plot before removing NAs

```{r}
# Test normalization with density plot --> medians are equal now
#This plot should be in the describe
df_norm_long |> 
  ggplot(aes(x=intensity, colour = sample)) +
  geom_density() +
  theme_classic()

```

## Density Plot

```{r}
# Check density -> Not ideal, many NA's distort distribution. Feature-wise would be ideal, b ut couldn't figure out how to operate NaIsMindet row-wise

df_nona_long |> 
  ggplot(aes(x=intensity, colour=sample)) +
  geom_density() +
  theme_classic()
```

## Summary Statistics / descriptive plots

-   here we could have some scatter plots, density plots etc.

## Scatter PlotsDensity plots

```{r}
df_no_na_long |> 
  ggplot(aes(x=intensity, colour=cell_type)) +
  geom_density() +
  theme_classic()
```
