## Make PCA plot

```{r}
library(tidyr)
library('ggbiplot')
library(graphics)
```



```{r}
# The new data-frame for df_no_na_wide is called : df_feature_wide.
# For creating a column sample as a guiding column use:
df_feature_wide |> 
  mutate(sample = str_c(cell_type,
                        replicate_n, sep = "_"),
         .before = cell_type)
``` 


```{r}

# Set the bitmap type to 'cairo' to avoid PNG issue
options(bitmapType = 'cairo')

#Input data tois wide format, excluding columns with missing data.
df_input <- df_no_na_wide |> select(-c('sample','cell_type')) |> 
  mutate(across(where(is.list), ~ sapply(., function(x) x[1]))) |> 
  na.omit() 
  
#Projecting data unto principal components (pc)
pc <- prcomp(df_input, center = FALSE, scale = FALSE)

#Gives overview of variability of PC
#print(pc)

#Gives an overview, you should be able to tell the variance already here even without the plot.
#summary(pc)

biplot <- ggbiplot(pc,
                   obs.scale = 0,
                   var.scale = 1,
                   var.factor = 1.5,
                   varname.adjust = 1.5,
                   varname.size = 3,
                   groups    = df_no_na_wide$cell_type, #visualises datagroups
                   ellipse   = TRUE,  #Probability elipse
                   ellipse.prob = 0.66, #Fraction of observations that should be in ellipse
                   circle    = FALSE,   #Unity circle representing structure correlation in variables
                   var.axes  = FALSE   #Variable vectors, can see correlation from if they're grouped
        )+
  theme(legend.position = 'top',aspect.ratio = 1)
  

print(biplot)
```

## Save plot

```{r}
ggsave(plot = biplot, filename = "PCA_on_proteingroups1.png", width = 20, height = 10, units = "cm", path = here("results"))
```
