## Libraries

```{r 01_libraries_and_options}
library(tidyr)
library(graphics)
library(broom)
source(here("R/99_functions.R"))
#options(bitmapType = 'cairo')
```

## PCA plots and variance analysis

```{r 01_principal_components}
df_input <- df_feature_wide |> select(-c('replicate_n','cell_type'))
  
colourby <- pull(df_feature_wide, 'cell_type')
   
#Projecting data unto principal components (pc)
pc <- prcomp(df_input, center = FALSE, scale = FALSE)

#Gives an overview, you should be able to tell the variance already here even without the plot
summary(pc)
```

```{r 03_pca_plot}
#Plots the principal component values (pc$x)  

pca_plot <- pc$x |> as.data.frame() |>
  ggplot(aes(x = PC1, y = PC2, color = colourby)) +
  geom_point(size = 2.5) +
  labs(title = 'Principal component analysis', 
       subtitle = 'Clustering of cell types on protein expression',
       color = 'Cell Type') +
  theme_classic() +
  theme(legend.position = 'right')
  
```

```{r 04_pc_variance_plot}
pc_varianceplot <- pc |>
  tidy(matrix = "eigenvalues") |>
  filter(PC <= 5) |>
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_classic() +
  ylab('Porportion of Variance (%)')
```

## Save plot

```{r 05_save_plots}
ggsave(plot = pca_plot, filename = "PCA_on_proteingroups_original.png", width = 15, height = 10, units = "cm", path = here("results"))

ggsave(plot = pc_varianceplot, filename = "pca_variance_barplot.png", width = 15, height = 10, units = "cm", path = here("results"))
```

## Plot PCA

```{r}
pca_plot
```

## Plot Variance explained

```{r}
pc_varianceplot
```
